name: Track control NG Doxygen
on: [push]

jobs:
  MRW-NG-Doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update package info
        run: sudo apt update -y
      - name: Install needed components
        run: sudo apt install -y qhelpgenerator-qt5 graphviz
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "."
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api-doc/html/
