name: Track control NG for model railways.
on: [push]

jobs:
    MRW-NG-Ubuntu:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - run: sudo apt update -y
         - name: Install needed components
           run: sudo apt install -y libqt5serialbus5-dev cppcheck libgtest-dev
         - name: QMake
           run: qmake -r
         - name: Build
           run: make -j `nproc`
         - name: CPP-Check
           run: make cppcheck
         - name: SCT Unit Tests
           run: make sct-unit
